-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mar. 26 oct. 2021 à 18:48
-- Version du serveur : 5.7.31
-- Version de PHP : 8.0.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `spectacle`
--

-- --------------------------------------------------------

--
-- Structure de la table `spectacles`
--

DROP TABLE IF EXISTS `spectacles`;
CREATE TABLE IF NOT EXISTS `spectacles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titre` varchar(200) NOT NULL,
  `nom` varchar(150) NOT NULL,
  `categorie` varchar(30) NOT NULL,
  `premiere` datetime NOT NULL,
  `derniere` datetime DEFAULT NULL,
  `ville` varchar(100) NOT NULL,
  `salle` varchar(100) NOT NULL,
  `visuel` varchar(150) NOT NULL,
  `alt` varchar(100) NOT NULL,
  `presentation` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `spectacles`
--

INSERT INTO `spectacles` (`id`, `titre`, `nom`, `categorie`, `premiere`, `derniere`, `ville`, `salle`, `visuel`, `alt`, `presentation`) VALUES
(8, 'Le Lac des Cygnes', 'Angelin Preljocaj', 'danse', '2020-10-07 20:00:00', '2022-06-11 20:00:00', 'Paris', 'Théâtre national de la Danse de Chaillot', '1635241905.jpg', 'groupe des danseuses avec cou penché en arrière', 'Un songe devient réalité : les amoureux de danse contemporaine en rêvaient depuis longtemps, Angelin Preljocaj crée enfin son Lac des cygnes. Quand « Preljo » révise nos classiques, il les révèle avec audace et génie. Son Roméo et Juliette, ses Mille et une Nuits et sa Blanche-Neige sont ainsi devenus des hits internationaux. Entouré de la crème des designers et stylistes, le chorégraphe crée des odyssées uniques, souvent charnelles, toujours méticuleuses de précision. Aujourd’hui, il a relevé le défi d’adapter le plus grand des ballets russes et sa danse des cygnes, monument de grâce et d’émotion. C’est avec ingéniosité et brio qu’il pénètre les brumes romantiques du lac où naît la romance entre le Prince Siegfried et le cygne Odette. Lorsque l’artiste, encore ado, a vu son premier Lac des cygnes à l’Opéra National de Paris, ce fut pour lui un choc. Son Lac des cygnes est à son tour un rendez-vous mémorable !'),
(9, 'Tartuffe - Théorème', 'Macha Makeïeff', 'théâtre', '2021-10-22 12:40:00', '2021-10-30 20:00:00', 'Marseille', 'La Criée', '1635245014.jpg', 'Personnage central déguisé en médecin avec chapeau pointu sur la tête', 'Après Trissotin ou Les Femmes Savantes en 2015, la directrice du Théâtre national de Marseille revient aujourd’hui à Molière avec Le Tartuffe, qu’elle transpose dans les années 1950. Une réflexion sur l’imposture, l’emprise, le consentement…\r\n\r\nVous avez intitulé votre spectacle TARTUFFE – Théorème. Quelle relation établissez-vous entre l’œuvre de Molière et celle de Pier Paolo Pasolini ?\r\n\r\nMacha Makeïeff : C’est avant tout un hommage que je voulais rendre à ce poète qui m’accompagne et m’éclaire depuis la fin de mon adolescence. Pasolini a toujours été très présent dans ma vie. Lorsque j’ai commencé à travailler sur Tartuffe, j’avais Théorème à l’esprit. Le livre et le film de Pasolini ont orienté ma lecture. Évidemment, ces deux textes ne sont pas des œuvres homothétiques. Mais avoir au préalable fréquenté Théorème m’a rassurée, m’a inspirée, m’a mise je crois au bon endroit pour entamer mon travail sur la pièce de Molière.\r\n\r\nRapprocher ces deux œuvres, est-ce aussi pour vous une façon d’envisager le personnage de Tartuffe comme un révélateur ?\r\n\r\nM.M : Exactement. Tartuffe est un personnage assez mystérieux, à tel point que son mystère est peut-être même un malheur. J’ai très envie de parler du malheur de Tartuffe, ce qui est une façon de se demander s’il existe vraiment, s’il n’est pas finalement qu’un fantasme qui s’effacerait à la fin de la pièce, laissant planer un doute sur la réalité de sa présence au sein de la maison. Dans Théorème, le personnage du visiteur est un envoyé qui révèle à chacun sa part d’ambivalence, de noirceur. Il déstructure puis restructure la famille dans laquelle il séjourne. Tartuffe fait la même chose. Et il pose également la question du consentement. Car Orgon (ndlr, le maître de la maison) est une victime très consentante. Il y a une forme de jouissance dans son acceptation à se sentir ainsi sous l’emprise de Tartuffe. Il y a une part d’amour dans ce don de soi, de ses biens…'),
(10, 'Sleeping d\'après Les belles endormies de Y. Kawabata', 'Serge Nicolaï', 'danse', '2021-10-27 20:30:00', '2021-11-06 20:30:00', 'Paris', 'Le Monfort Théâtre', '1635246191.jpg', 'Buste de femme avec maquillage de Nô', 'Librement inspiré par le roman Les belles endormies de l’auteur japonais Yasunari Kawabata, Serge Nicolaï crée Sleeping, une traversée onirique où vivants et morts se rejoignent et où différents arts se mêlent  –  jeu, masques nô, danse, musique, écrin vidéo. Avec Yoshi Oïda, célèbre comédien de Peter Brook, dans le rôle principal.\r\n\r\nQuelle est la genèse de cette création ?\r\n\r\nSerge Nicolaï : Le point de départ fut mon désir de travailler avec des masques de Nô, particulièrement précis, rigoureux et puissants. Ce désir m’a conduit à rechercher un texte qui puisse accepter cette forme singulière, très exigeante pour l’acteur. Je me suis plongé dans la littérature contemporaine japonaise, qui recèle nombre de nouvelles très imagées propices à une adaptation scénique, et j’ai découvert par hasard Les belles endormies (1961) de Yasunari Kawabata, prix Nobel de littérature 1968, dont l’œuvre est traversée par les thèmes de la solitude et de la mort. Dans ce roman mystérieux, l’un de ses écrits les plus célèbres, le vieil Eguchi se rend dans une maison étrange où des jeunes filles endormies par de puissantes drogues accueillent des hommes âgés qui les paient pour passer la nuit auprès d’elles. Cette situation initiale scabreuse ouvre la voie vers une méditation apaisée sur la vie qui s’enfuit, vers une introspection profonde sur l’existence. Métaphoriques plus que réelles, les belles endormies ravivent en effet les souvenirs de femmes aimées – mère, amante, épouse…  – dans une sorte de bain de jouvence à la lisière du monde des morts.'),
(13, 'La seconde surprise de l\'amour, d\'après Marivaux', 'Alain', 'théâtre', '2021-11-05 20:00:00', '2021-12-04 20:00:00', 'Paris', 'L\'Odéon-Théâtre de l\'Europe', '1635254935.jpg', 'Homme en imper quittant la scène, laissant derrière lui les personnes de la maison en suspens', 'Après La Double Inconstance en 1982, Alain Françon met en scène La Seconde Surprise de l’amour. Une création d’une grande inspiration qui fait éclater les hauteurs et profondeurs de l’être.\r\nOn a presque l’impression d’entendre La Seconde Surprise de l’amour pour la première fois. Non que notre mémoire nous fasse défaut, oubliant les dépits et les convoitises auxquels sont confrontés la marquise et le chevalier au centre de la pièce de Marivaux. Ces êtres aux cœurs blessés se laissent surprendre par des émotions impromptues. On le sait. On connaît tout ceci. Et les marivaudages aux tons pastel qui vont souvent avec. Mais dans la mise en scène d’Alain Françon, ces tours et détours amoureux résonnent d’une tout autre façon. Dans une immédiateté fortement expressive qui, de prime abord, déconcerte. Les répliques se déploient comme on ne s’y attendait pas : hâtives ou curieusement syncopées, joyeusement facétieuses ou abruptement débordantes. Peu à peu, le trouble fait place à l’enthousiasme. Car cette manière décalée de dire, de proférer en sculptant les phrases, rend profondément singuliers et vivants les chemins de vie de la marquise et de sa suivante, Lisette, qui tente de tirer sa maîtresse de l’abattement dans laquelle l’a précipitée son veuvage. De Lubin, valet du chevalier qui veut séduire Lisette. Du comte, prétendant malheureux de la marquise. D’Hortensius, pédant lettré qui a un faible pour Lisette.'),
(16, 'Guérillères', 'Marta Izquierdo Munoz', 'arts-vivants', '2021-10-26 20:00:00', '2021-10-29 20:00:00', 'Reims', 'Manège-Scène nationale de Reims', '1635256503.jpg', 'Trois danseur.se.s dans une scène d\'hystérie', 'Après s’être attachée à l’image de la majorette dans Imago-go, Marta Izquierdo Muñoz convoque la puissance des « guérillères » pour poursuivre ses recherches sur les groupes féminins et l’ambiguïté de certaines figures de la culture populaire. C’est à la suite d’un voyage en Colombie, dans une jungle récemment désertée par les guérilleros des FARC, que la chorégraphe s’est mise à imaginer la vie d’une communauté de femmes combattantes, en position d’attente devant un ennemi invisible. Comme souvent chez Marta Izquierdo Muñoz, les personnages sont des hybrides entre êtres de fiction et modèles réels. Pour cette création, elle s’est inspirée de la communauté campée par Monique Wittig dans son manifeste poétique Les Guérillères mais aussi des Amazones de la mythologie grecque et autres super-héroïnes. Tout un imaginaire qu’elle a choisi de revisiter à sa façon, drôle et fantasque. La pièce révèle ainsi un trio qui, à l’écart de toute civilisation, réinvente ses propres règles, ses propres jeux et ses propres armes, dans l’attente d’un combat qui n’arrive jamais. Au fil de rituels aussi singuliers que burlesques, cette drôle de tribu déploie une gestuelle inspirée de films de science-fiction, de séries B ou encore de certains jeux vidéo. Une épopée chorégraphique qui vogue en eaux douces-dingues entre le souffle de la poésie lyrique et l’imaginaire débridé d’une chorégraphe, nourrie de la contre-culture de la movida madrilène.'),
(17, 'Zingaro', 'Bartabas', 'arts-vivants', '2021-10-19 20:30:00', '2021-12-31 20:30:00', 'Aubervilliers', 'Théâtre équestre Zingaro', '1635257181.jpg', 'Femme en équilibre sur homme sur cheval au galop', 'En 1984, Bartabas crée son premier cabaret équestre. 37 ans plus tard, il y a peu encore le temps ordinaire d’une carrière professionnelle complète, il renoue avec cette forme et ouvre son spectacle sur le discours d’Isaac Bashevis Singer lors de sa réception du Prix Nobel de littérature en 1978. Celui-ci y explique pourquoi il écrit encore en yiddish alors que c’est une langue en voie de disparition. On aurait du mal à ne pas voir ici une métaphore du travail de Bartabas et de sa troupe à qui on pourrait également demander pourquoi ils emploient encore cette langue du théâtre équestre à l’heure de la 5G et de l’animalisme. En quelques années à fréquenter les théâtres, c’était pour moi une première fois à Zingaro. J’allais avec envie et un peu de méfiance découvrir le travail de Bartabas, ce monument du spectacle équestre installé depuis plusieurs décennies du côté du Fort d’Aubervilliers. Je ne peux que regretter de ne pas l’avoir fait plus tôt.'),
(18, 'Les Furtifs, d\'après le roman d\'Alain Damasio', 'Compagnie Roland Furieux', 'musique', '2021-11-12 20:00:00', '2021-11-13 20:00:00', 'Metz', 'Cité musicale de Metz-Arsenal', '1635258158.jpg', 'Vue d\'orchestre de la scène avec halo bleu en fond', 'La compagnie musicale Roland furieux, en résidence à la Cité musicale de Metz, poursuit son exploration de la littérature contemporaine en s’emparant du roman d’Alain Damasio, une dystopie qui dissèque une société aliénée par le numérique et le capitalisme.\r\nQuestionner le tissage entre littérature et création musicale, tel est le pari de la compagnie Roland furieux, créée par la metteuse en scène Laetitia Pitz qui collabore depuis plusieurs années avec le musicien Xavier Charles. Leur écriture scénique interroge selon leur description « la physicalité du son et de la voix, et met l’écoute au centre du processus ». Après avoir travaillé sur un roman d’Antoine Volodine dans leur spectacle Mevlido appelle Mevlido puis de Lutz Bassmann (autre nom de Volodine) avec Danse avec Nathan Golshem, ils créent cette fois, d’après le roman d’Alain Damasio, Les Furtifs, une « partition science-fictionnelle pour voix parlées et ensemble instrumental ». Dans ce pavé de 700 pages, publié en 2019 et couronné l’année suivante par le Grand prix de l’Imaginaire, l’auteur situe son action en 2040, dans une société envahie par le numérique et privatisée par les firmes multinationales.'),
(19, 'A poils', 'Alice Laloy/Compagnie s\'appelle Reviens', 'arts-vivants', '2021-10-29 14:30:00', '2022-05-06 14:30:00', 'Rennes', 'Festival &quot;Marmaille en fugues&quot;', '1635259779.png', 'Poils-cheveux d\'hommes bourrus de différentes couleurs', 'La mise en scène d’Alice Laloy est assise sur deux éléments qui évoluent au fil du spectacle : les émotions et les éléments matériels. Les enfants sont face à 3 hommes à la taille et à la corpulence démesurées et vêtus de très longs cheveux de couleurs. Leurs allures bourrues dans l’organisation de la scène se traduisent peu à peu en une générosité et une tendresse guidant les enfants à l’élaboration de ce spectacle participatif. Cette adhésion se fait naturellement dans la quête du mystère qui entoure ce spectacle. Dans leurs rapports quelque peu directifs, nos trois poilus conjuguent jeux et pédagogie s’assurant ainsi une pleine et entière participation des enfants. Le résultat final inattendu repose sur une transformation de l’espace et un changement notable du comportement de nos 3 dockers. Ils déversent une tendresse insoupçonnée et semblable à celle du cocon qu’ils ont élaboré avec l’aide des enfants. Un déferlement de lumières et de couleurs invite ce jeune auditoire à parcourir avec eux un joyeux chemin pavé de musique. Ce spectacle constitue une magnifique parenthèse théâtrale qui se signale par sa beauté intrinsèque et son extravagance joyeuse. Le tout baigné dans une harmonie de couleurs et sons !'),
(20, 'L\'Odyssée sensorielle', 'MNHN', 'arts-vivants', '2021-10-26 10:00:00', '2021-11-26 19:00:00', 'Paris', 'Muséum national d\'histoire naturelle', '1635262197.jpg', 'Public équipé de lunettes de réalité virtuelle', 'ENQUÊTE - Après des débuts chaotiques, ce mouvement qui mêle cinéma, arts, spectacle vivant et technologie s’impose désormais partout. Le public plébiscite ces propositions proches du divertissement et résolument inventives.\r\n\r\nParis, Muséum national d’histoire naturelle (MNHN). Dans le noir, un rugissement retentit suivi d’un cri d’oiseau affolé. Les pieds dans une mare éclairée par la lune, le visiteur devine que proies et prédateurs de la savane l’entourent. Tel Alice dans le pays des merveilles, il file sous terre. Même avec le masque, des effluves d’humus et de truffe chatouillent les narines. Sous les eaux arctiques, à la rencontre des cachalots, une odeur ambrée prend le relais… «Cette promenade à travers huit écosystèmes est une expérience d’un nouveau type, une première mondiale», se félicite Bruno David, président du MNHN, en évoquant «L’Odyssée sensorielle», la nouvelle attraction du lieu. Il espère que les milliers de visiteurs attendus auront davantage d’empathie pour le monde vivant, aussi beau que fragile. «Pour cette immersion qui mêle l’odeur, la vue et le son, deux cents scientifiques, scénographes, ingénieurs du son et chimistes ont travaillé ensemble pendant six ans», souligne le producteur.'),
(21, 'Le concert du jour', 'La Philharmonie de Paris', 'musique', '2020-03-23 20:30:00', '2022-03-31 20:30:00', 'Paris', 'Web', '1635269516.jpg', 'Affiche virtuelle représentant une esplanade incurvée', 'Chaque soir à 20 h 30, le site Internet de La Philharmonie de Paris met en ligne, depuis lundi 23 mars, un concert différent, tiré de sa programmation passée, que cela soit de la musique baroque, classique ou contemporaine, du jazz, de la pop ou de la chanson. Après des soirées consacrées à la pianiste Martha Argerich, au groupe pop The Divine Comedy, à la Messe pour le temps présent, de Pierre Henry ou un Higelin symphonique, la semaine de lundi 6 au dimanche 12 avril se révèle tout aussi passionnante. Avec notamment le concert inaugural de l’ouverture au public de La Philharmonie, le 16 janvier 2015, pour un programme Philidor, Charpentier, Mondonville et Rameau par Les Arts florissants dirigés par William Christie (mardi 7 avril), la présentation de la 200 Motels Suites, de Frank Zappa (jeudi 9 avril) ou le concert de Rone, qui mêle électro, trio à cordes et percussions (samedi 11 avril).'),
(22, 'Open online archives', 'Neil Young', 'musique', '2020-03-18 00:00:00', '2022-12-31 00:00:00', 'Canada', 'Web', '1635271538.jpg', 'Boîte à archives recouverte de stickers-Page d\'accueil du site de NY', 'Le rocker canadien Neil Young, âgé de 74 ans, n’a jamais été avare de sessions acoustiques intimistes. Depuis le 18 mars, il propose régulièrement des « sessions au coin du feu » (« Fireside sessions ») filmées par son épouse Daryl Hannah. Pas si confiné d’ailleurs, comme on peut le voir lors de sa dernière session mise en ligne le 1er avril, où il marche sur la neige, la guitare en bandoulière. « Une production maison, quelques chansons, un petit moment passé ensemble », à voir uniquement sur son site officiel, Neil Young étant notoirement allergique aux réseaux sociaux et plus particulièrement Facebook.\r\nAutre geste généreux de sa part, l’auteur de l’hymne Rocking a Free World a rendu accessible gratuitement l’intégralité de son site Neilyoungarchives.com. Véritable mine d’or pour ses admirateurs, cette plateforme initialement payante, inaugurée en 2017, rassemble tout ce que l’artiste a enregistré depuis ses débuts en 1963, soit des centaines d’albums, concerts ou vidéos, mais aussi des films réalisés sous le pseudonyme Bernard Sharkey. La navigation de cette colossale source en ligne peut parfois s’avérer déroutante, mais elle mérite le détour. Pour en profiter, il faut préalablement s’inscrire, le site proposant en temps normal un abonnement de 12 euros annuel.'),
(23, 'Les Concerts à la maison', 'Artistes divers', 'musique', '2020-03-20 12:00:00', '2022-12-31 12:00:00', 'Web', 'Page Facebook d\'Arte', '1635272307.jpg', 'Bannièere des Concerts à la maison sur la page Facebook d\'Arte', 'Depuis le début du confinement, le site Arte Concert a décidé de mettre à disposition plus de 600 concerts, à voir et à revoir en accès libre. L’occasion notamment de voir les adieux à la scène de l’icône folk Joan Baez à L’Olympia. Parallèlement, la plate-forme créée en 2009 par la chaîne de télévision franco-allemande a inauguré un rendez-vous quotidien sur Facebook, Les Concerts à la maison : du lundi au vendredi, à midi, la page Facebook d’Arte Concert propose des concerts intimistes en direct.\r\n\r\nLa semaine dernière, parmi les artistes invités, la chanteuse Emel Mathlouthi a ainsi donné un concert sur les toits de Tunis, mais aussi le rocker alsacien Rodolphe Burger en direct depuis son home studio, ou encore Chapelier Fou, Yael Naim, Camélia Jordana... Des sessions qui nous donnent aussi le privilège de voyager avec ces musiciens depuis leur intérieur. Pour être tenu au courant des prochaines, il suffit de suivre le compte Arte concert sur Twitter.\r\nhttps://www.facebook.com/ARTEConcert/');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
